CREATE DATABASE RPGDIGONLINEDB

USE RPGDIGONLINEDB

CREATE TABLE Usuarios(
	UsuarioID INT PRIMARY KEY IDENTITY,
	Email VARCHAR(100) UNIQUE NOT NULL,
	Senha VARCHAR(255) NOT NULL
)

CREATE TABLE Classes(
	ClasseID INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(50) UNIQUE NOT NULL,
	Descricao VARCHAR(255) NOT NULL
)

CREATE TABLE Personagem(
	PersonagemID INT PRIMARY KEY IDENTITY,
	NomePersonagem VARCHAR(15) UNIQUE NOT NULL,
	UsuarioID INT UNIQUE FOREIGN KEY REFERENCES	Usuarios(UsuarioID),
	ClasseID INT FOREIGN KEY REFERENCES	Classes(ClasseID)
)

CREATE TABLE Habilidades(
	HabilidadeID INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(100) UNIQUE NOT NULL
)

CREATE TABLE ClasseHabilida(
	ClasseID INT FOREIGN KEY REFERENCES	Classes(ClasseID),
	HabilidadeID INT FOREIGN KEY REFERENCES	Habilidades(HabilidadeID)
)

